---
- name: Capture network traffic on the control node
  hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

  tasks:
    - name: install tcpdump
      apt:
         name: tcpdump

    - name: Fetch PCAP file
      fetch:
        src: capture.pcap
        dest: "/home/ivan/CPE243_HOA8.1/"

    - name: Make it executable the pcap
      command: chmod +x /home/ivan/capture.pcap

